spring:
  application:
    name: zoo
  profiles:
    active: dev

logging:
  config: classpath:logback-${spring.profiles.active}.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS