version: 0.0
os: linux
files:
   - source: content/WAR_NAME
     destination: DESTINATION_PAHT
hooks:
  ApplicationStop:
    - location: scripts/Initialize.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/ApplicationStop.sh
      timeout: 300
      runas: root
    - location: scripts/DeleteWar.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/ValidateService.sh
      timeout: 300
      runas: root
    - location: scripts/UpdateApiDoc.sh
      timeout: 300
      runas: root